on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: release – ${{ matrix.platform.os_name }}
    strategy:
      matrix:
        toolchain: [stable]
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v3
      - name: build executable
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ubi
          changes-file: ""
          target: ${{ matrix.platform.target }}
        if: matrix.toolchain == 'stable'
